name: Test
on: pull_request
permissions:
  checks: write
  contents: write
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y clang-format
    - uses: manicmaniac/lint-action@clang-format
      with:
        auto_fix: true
        clang_format: true
        clang_format_auto_fix: true
